version: '3'

services:

  web: # Web Interface
    image: killrvideo/killrvideo-web:3
    ports:
      - "3000:3000" # Exposes port to be available externally
    depends_on:
      - backend # Needs Backend to be running
    environment:
      KILLRVIDEO_LOGGING_LEVEL: debug # More logging

  # Service implementation - use docker-compose-backend-external.yaml if running services in IDE
  backend: # KillrVideo Backend 
    image: killrvideo/killrvideo-java
    ports:
      - "50101:50101" # Exposes port to be available. Kompose tool needs that to create a k8s service and make backend available for other services.
    depends_on:
      - dse  # Needs DSE to be running
    environment:
      KILLRVIDEO_LOGGING_LEVEL: debug # More logging
      KILLRVIDEO_DSE_CONTACT_POINTS: dse
  
  # Datastax Studio provides convenient web interface to work directly with DataStax Enterprise
  studio:  
    image: datastax/dse-studio:6.7.0
    ports:
      - "9091:9091" # Exposes port to be available externally
    depends_on:
      - dse # Needs DSE to be running
    environment:
      DS_LICENSE: accept

  # DataStax Enterprise Database
  dse: 
    image: datastax/dse-server:6.7.4
    command: [ -s -g ] # Run with Search and Graph capabilities enabled
    ports: # Exposes ports to be available.
      - "9042:9042" # Exposes DSE port
      - "8983:8983" # Exposes DSE Search port
      - "8182:8182" # Exposes DSE Graph port
    environment:
      DS_LICENSE: accept # Accept licence on start
    cap_add:
      - IPC_LOCK # Allow DSE to lock memory with mlock
    ulimits:
      memlock: -1

  # One-Time Bootstrap Container, configures DSE to have required keyspaces etc.
  dse-config: 
    image: killrvideo/killrvideo-dse-config:3
    depends_on:
      - dse # Needs DSE to be running

  # Sample Data Generator, imitates behaviour of users on the killrVideo website. 
  # Adds comments and rates videos, upload new videos and so on.
  generator: 
    image: killrvideo/killrvideo-generator:3
    depends_on:
      - backend # Needs Backend to be running
    environment:
      KILLRVIDEO_LOGGING_LEVEL: debug # More logging

