version: '3'

#
# docker-compose-backend-external.yaml
#   Simple compose file for running containers comprising the KillrVideo application and supporting infrastructure,
#   minus the Backend services, which may be run at the command line or in an IDE using the instructions in the README.
#   For more complex configuration options including metrics, external volumes, OpsCenter,
#   etc., see https://github.com/KillrVideo/killrvideo-docker-common
services:

  web: # Web Interface
    image: killrvideo/killrvideo-web:3.0.1
    ports:
      - "3000:3000" # Exposes port to be available externally
    environment:
      KILLRVIDEO_LOGGING_LEVEL: debug # More logging
    extra_hosts:
      - backend:$KILLRVIDEO_BACKEND
  
  # DataStax Enterprise Database
  dse: 
    image: datastax/dse-server:6.7.7
    command: [ -s -g] # Run with Search and Graph capabilities enabled
    ports: # Exposes ports to be available.
      - "9042:9042" # Exposes DSE port
      - "8983:8983" # Exposes DSE Search port
      - "8182:8182" # Exposes DSE Graph port
    environment:
      DS_LICENSE: accept # Accept licence on start
    cap_add:
      - IPC_LOCK # Allow DSE to lock memory with mlock
    ulimits:
      memlock: -1

  # One-Time Bootstrap Container, configures DSE to have required keyspaces etc.
  dse-config: 
    image: killrvideo/killrvideo-dse-config:3.0.0
    depends_on:
      - dse # Needs DSE to be running

  # Sample Data Generator, imitates behaviour of users on the killrVideo website. 
  # Adds comments and rates videos, upload new videos and so on.
  generator: 
    image: killrvideo/killrvideo-generator:3.0.2
    environment:
      KILLRVIDEO_LOGGING_LEVEL: debug # More logging
      KILLRVIDEO_YOUTUBE_API_KEY: ${KILLRVIDEO_YOUTUBE_API_KEY}
    extra_hosts:
      - backend:$KILLRVIDEO_BACKEND
