# ----------------------------------------------------------------------
# Global Settings
# ----------------------------------------------------------------------
spring:
  output:
    ansi:
      enabled: ALWAYS
  profiles:
   active:
    # Messaging profiles are exclusive : Enable either messaging_memory or messaging_kafka, not both
    - messaging_memory
    #- messaging_kafka
    
# ----------------------------------------------------------------------
# KillrVideo Backend Services
# ----------------------------------------------------------------------
killrvideo:

  application:
    name: killrvideo
    
  # ----------------------------------------------------------------------
  # Enable/Disable services in deliverable (MODULES)
  # ----------------------------------------------------------------------
  grpc-server: 
    port: 50101
    services:
      comment: true
      rating: true
      search: true
      statistic: true
      videoCatalog: true
      user: true
      suggestedVideo: true
  
  # ----------------------------------------------------------------------
  # Cassandra configuration
  # ----------------------------------------------------------------------
  dse:
    # You can override this value by defining env var: KILLRVIDEO_DSE_CONFIGURATION_FILE
    configFile: application.conf
    maxNumberOfTries: 50
    delayBetweenTries: 5
    search:
      ignoredWords: and,or,but,nor,so,for,yet,after,as,till,to,the,at,in,not,now,of,if,this,an,are,all,about,along,by,is,it,on,why,be,can,com,get,out,see,some,new,these,that,thing,things,wish,known,say,they,had,here,like,live,let,do,with,what,when,www,watch,will,http,https,us,you,your,more,his,her,they,them,their,me,we,near,bit,ly,back,meet,know,key,video,various,find,only,from,kind,channel,comments,below,check,right,full,while,gets,up,each,no,buy,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z
    mutation-error-log: /tmp/killrvideo-mutation-errors.log
    
  # ----------------------------------------------------------------------
  #   # Used only if profile 'messaging_memory' is enabled
  # ----------------------------------------------------------------------
  messaging.memory:
    minThreads: 5
    maxThreads: 10
    ttlThreads: 60
    queueSize: 1000
  
  # ----------------------------------------------------------------------
  # Used only if profile 'messaging_kafka' is enabled
  # ----------------------------------------------------------------------  
  kafka:
     brokers: kafka
     port: 8082
     ack: 1
     consumerGroup: killrvideo
     destinations:
       errors: topic-kv-errors
       videoRated: topic-kv-videoRating
       commentCreated: topic-kv-commentCreation
       userCreated: topic-kv-userCreation
       youTubeVideoAdded: topic-kv-videoCreation
