version: '3'

services:
  cassandra:
    image: cassandra:3.11.6
    ports:
      - 7000:7000
      - 7001:7001
      - 7199:7199
      - 9042:9042
    ulimits:
      memlock: -1
    # If you want to save data directories across runs
    # volumes:
    #   - ~/cassandra/:/var/lib/cassandra/data

  spring_boot:
    depends_on:
      - cassandra
    build: .
    image: reservation-service:latest
    ports:
      - "8080:8080"
    environment:
      CASSANDRA_CONTACT_HOST: cassandra
      CASSANDRA_CONTACT_PORT: 9042

# To run cqlsh
#  docker-compose exec -it cassandra cqlsh
    
  